Description: >
  UdaPeople backend stack.

Parameters:
  ID:
    Description: Unique identifier.
    Type: String

Resources:
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub UdaPeople-${ID}
      GroupDescription: Allow port 22, port 3030, 9100 prometheus.
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 3030
          ToPort: 3030
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 9100
          ToPort: 9100
          CidrIp: 0.0.0.0/0

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      SecurityGroups:
        - Ref: InstanceSecurityGroup
      KeyName: udacity # If you use another key pair name, you should change this value to match.
      # If this ami id is not available for you, you can find another (https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/finding-an-ami.html)
      # Ubuntu 18 or higher works fine
      ImageId: ami-068663a3c619dd892 
      Tags:
        - Key: Name
          Value: !Sub backend-${ID}
      UserData: 
        Fn::Base64: !Sub |
              #!/bin/bash -xe
              # install node exporter for promethues
              wget https://github.com/prometheus/node_exporter/releases/download/v1.0.1/node_exporter-1.0.1.linux-amd64.tar.gz
              tar xzf node_exporter-1.0.1.linux-amd64.tar.gz
              cp node_exporter-1.0.1.linux-amd64/node_exporter /usr/local/bin/node_exporter
              rm -rf node_exporter-1.0.1.linux-amd64.tar.gz node_exporter-1.0.1.linux-amd64
              vi /etc/systemd/system/node-exporter.service
              vi /etc/systemd/system/node-exporter.service
              systemctl daemon-reload
              systemctl enable node-exporter
              systemctl start node-exporter
              systemctl status node-exporter
